### ISSUE TITLE
rpmlint complains about invalid invalid-lc-messages-dir

### ISSUE THREAD

**Issue by ndias** [mrvladus/Errands#102]
invalid-lc-messages-dir /usr/share/locale/zh_tw/LC_MESSAGES/errands.mo

Changing /usr/share/locale/zh_TW/LC_MESSAGES/errands.mo solves the problem

**Comment by mrvladus** [comment]
Fixed in 64c2fd1c436bcd1d358d868dbe2beebcdfddcb5a and de8b47b8591856de77871768869d6a93731c2993
