### ISSUE TITLE
Run Errands in the background

### ISSUE THREAD

**Issue by ndias** [mrvladus/Errands#103]
It is possible to add an option to close the application to systray?

**Comment by mrvladus** [comment]
No, GTK4 doesn't have support for tray indicators. The only possible option is to run app in the background all the time, but it is not needed until I add functionality to send notification when Tasks due time is reached. Something like a timer app, that you can close, but it is still running the timer you set.

**Comment by ndias** [comment]
Ok, my bad, not very clear from my part.
Basicaly support libappindicator https://extensions.gnome.org/extension/615/appindicator-support/ in gnome-shell for example

**Comment by ndias** [comment]
What I seek is the possibility to click an icon and the application opens and show me my tasks, right now I must click several times to open or search the application, yes in gnome-shell I have the dock that if the application is running is one click, but then again will switch to the workspace that the application was open, and I don't want that

**Comment by mrvladus** [comment]
In GNOME 45 there is background apps menu that you can open background apps with a click now
![Снимок экрана от 2023-12-05 19-47-58](https://github.com/mrvladus/Errands/assets/64690334/458e8db2-d702-467c-9d7d-7e754c6eace6)
Maybe it will be improved in the future, but for now it is all there is

**Comment by mrvladus** [comment]
I'll add option for running app in the background in the next major release

**Comment by brainwo** [comment]
This feature would be so desirable.
I tried comparing this app with Blender, it took almost as long time to open (Blender is 1.9 seconds, Errands took 1.8 seconds). Blender installed from system package manager, Errands installed from compiling the source.
I find this loading time is unacceptable, some apps like Blender get away with this by drawing the window frame first (at 1.2 seconds). Everytime I open Errands, I'm not sure whether I did open it or not.

I'm not sure if the loading speed can be improved so I leave it as a comment here instead of creating a new issue.

**Comment by mrvladus** [comment]
@brainwo I drastically improved perfomance in new version. Now it opens almost immediately, even with hundreds of tasks.

**Comment by brainwo** [comment]
Seems like the AUR package is outdated, thanks for responding

**Comment by mrvladus** [comment]
@brainwo I didn't released new version yet :) I think in the end of this week.

**Comment by mrvladus** [comment]
Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)

**Comment by Klaaktu** [comment]
Currently with "Run in Background" toggled off, Errands will still run at login and recreate the autostart file if it's removed. Is it possible for the toggle to also disable the auto start?

**Comment by mrvladus** [comment]
@Klaaktu I've just added setting for disabling autostart in 1a9a2c8cbb52ebd0d1ff5457ae9013dd43083fdc. Will be in the next update ;)
