### ISSUE TITLE
Appdata screenshots are too tall

### ISSUE THREAD

**Issue by bertob** [mrvladus/Errands#106]
Appdata screenshots [should ideally be smaller than 1000x700 pixels](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), otherwise the UI is hard to see on the thumbnails in app stores. The height is particularly important for this since that's usually what causes it to be scaled.

This is becoming more important now because we're planning to use app screenshots for "featured" banners on Flathub :)

**Comment by mrvladus** [comment]
Thanks! I'll change them :)

**Comment by mrvladus** [comment]
Changed screenshots in [45.1](https://github.com/mrvladus/Errands/releases/tag/45.1).
