### ISSUE TITLE
multiple task lists false claims

### ISSUE THREAD

**Issue by madhums** [mrvladus/Errands#110]
In the readme, you mention "multiple task lists" are supported and the [screenshot](https://github.com/mrvladus/Errands/blob/main/screenshots/main.png) supports that. But when I install the app, the left sidebar only shows "Deleted tasks". 

I am using Errands with Nextcloud sync. Am I missing anything?

**Comment by mrvladus** [comment]
Added in [45.1](https://github.com/mrvladus/Errands/releases/tag/45.1).

**Comment by madhums** [comment]
That's great! Thank you! Has it been published on flathub?

**Comment by mrvladus** [comment]
@madhums I've pushed it on flathub. Will be available in a couple of hours.
