### ISSUE TITLE
Plus Sign "Slots" stuck open

### ISSUE THREAD

**Issue by Natetronn** [mrvladus/Errands#111]
Often, when moving tasks around, you'll see the empty task slots with a plus sign and an "ants" border, but they don't close unless you're very careful to move the dragged item in a very specific manner:

![image](https://github.com/mrvladus/Errands/assets/582149/88bfe930-2bb4-4137-8b9b-708bba9a46e4)

~~I'm still trying to figure out the trick to getting them closed, so can't say what is the solution or why this happens.~~  

I think if you drag an item down, a slot opens up above its parent, if you drag it a bit further down, the slot below the item you're dragging opens up, if you set the item down at that point they both stay open. If you drag the item slightly up again, they both close at that point.

Closing and reopening the app closes the empty slots.

**Comment by mrvladus** [comment]
Hi! What version are you running?

**Comment by Natetronn** [comment]
@mrvladus I think it's the latest (45.1), although I think I saw this issue before this major update as well.

**Comment by mrvladus** [comment]
Can you record a video? I can't replicate it.

**Comment by Natetronn** [comment]
https://youtu.be/L0QJnH9ldUM

**Comment by mrvladus** [comment]
@Natetronn I've tested it in Manjaro VM and found that it is KDE bug, along with the strange black background of app icon, that is KDE bug too. I fixed this issues in fea921fc853a832c2c31881fc99147f648db352d and 9633b79557a75a22c56853fb47049ecd1647f00a, so in the next release all should be fine.

**Comment by Natetronn** [comment]
Thank you very much!
