### ISSUE TITLE
v45.1 won't run 

### ISSUE THREAD

**Issue by WebShapedBiz** [mrvladus/Errands#112]
Hi.
I used the previous version without any issues but today, after updating to v45.1 the app won't run. I just see a "loading" icon for some time and that's all.
This is what I'm getting in the console:
```
[DEBUG] Starting Errands 45.1
[DEBUG] Data: convert data file
[DEBUG] Initialize GSettings
[INFO] Data: Create '5bf5c157-e96b-4e78-8e29-cece58c8cc0c' list
```
I'm using elementaryOS 6.1 (based on Ubuntu 20.04.6 LTS) and installed the app using Flatpak.

Cheers.

**Comment by mrvladus** [comment]
Please, try to reinstall the app

**Comment by WebShapedBiz** [comment]
No luck. Just the message in the terminal is different. Now is just:
`[DEBUG] Starting Errands 45.1
`

**Comment by mrvladus** [comment]
Did you had sync turned on or off?

**Comment by WebShapedBiz** [comment]
Off.

**Comment by mrvladus** [comment]
Is your system updated? And try to reboot too.

**Comment by WebShapedBiz** [comment]
It worked after the reboot. I don't understand how a Flatpak app needs a reboot but it's fine now.

Thank you for your time and effort.

**Comment by mrvladus** [comment]
Sometimes flatpak is behaving strange, a often have this exact problem with firefox :)
