### ISSUE TITLE
Start and end dates

### ISSUE THREAD

**Issue by madhums** [mrvladus/Errands#113]
In the task properties, it says "start" twice. I am guessing one is end date, am I right?

![image](https://github.com/mrvladus/Errands/assets/123815/fc37c2e1-4718-4aae-b610-2597fde682b6)

**Comment by madhums** [comment]
Also setting the date, doesn't seem to save it. Once I set it and go back to the task, the date is not remembered anymore.

**Comment by mrvladus** [comment]
Yes, i already fixed it in 1781520415a42b94c4d17dbae221064337b6e899

**Comment by mrvladus** [comment]
There is "Save" button on top

**Comment by madhums** [comment]
Great that it is fixed. Yes I've been saving it but it still isn't saved.
There's one more thing: when you click on the date picker and try to set today's date, nothing happens. I should be able to set today's date.

**Comment by madhums** [comment]
I see the same issue with tags, they aren't saved. Not sure if it is related to this but I am happy to create a new issue if you need.

**Comment by mrvladus** [comment]
I tried set date with nextcloud sync, and it sets it successfully, strange... Tags working too, except when I delete all of them, then they not saving.

**Comment by mrvladus** [comment]
Fixes tags in 8bb93f344451b49a97437b01208be29655745556

**Comment by mrvladus** [comment]
Can you copy terminal output, when you set date?

**Comment by madhums** [comment]
With regards to tags, it looks like the tag is set in nextcloud but it is not retained in errands after it is fetched (Note that this is a task that was pre 45.1 release)

Logs:

```
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Getting tasks from remote
[DEBUG] Sync: Getting tasks from remote
[DEBUG] Sync: Update task on remote: d5d2deaf-53ed-4dd8-8242-36890041003a
[DEBUG] Sync: Getting tasks from remote
[DEBUG] Lists: Update UI...
[DEBUG] Task list tasks: Update UI
[DEBUG] Task list 8f402eaa-a49c-11ee-86da-2585302f7ba2: Update UI
[DEBUG] Details: Update info
[DEBUG] Task list 0E533784-0B5C-4374-B64C-2AF7C5EB827E: Update UI
[DEBUG] Details: Update info
```

I see the tag in nextcloud as well. 
The tags seem to work for newly created tasks post 45.1 release. For the old tasks, tags are not updated in UI for some reason, although they are set in nextcloud.

With regards to date: The UI doesn't enable "save" button when the date is today. In other words nothing happens when the datepicker opens and when I click on today's date. This is related to UI I suppose. I see that the date is saved to nextcloud, so that works.

Here is a video demonstrating the latter
[Screencast from 2023-12-28 10-45-22.webm](https://github.com/mrvladus/Errands/assets/123815/b736add9-49b4-455f-b1a6-5dd670eabd58)

Couple of things I noticed:
- [ ] It would be nice to have some kind of indicator when the task is syncing (for example next to the window title Errands, you can have a spinner)
- [ ] The details panel opens to the left. It would be nice to have this on the right side instead of in the middle.
- [ ] When the task is synced/updated, I notice that sometimes the details panel gets closed automatically. Perhaps this could be left as is, to avoid any surprises to the user. It could be that the user is still making changes to the task...

Do these resonate with you? if so, are you willing to take these as feedback to better UX? 
Really appreciate all the effort you've put in so far 🙏🏽 ❤️

**Comment by mrvladus** [comment]
> With regards to date: The UI doesn't enable "save" button when the date is today. In other words nothing happens when the datepicker opens and when I click on today's date. This is related to UI I suppose. I see that the date is saved to nextcloud, so that works.

I see what you mean. I just use "Now" button for setting today's date and never clicked on today in calendar widget.  I'll try to fix it. 

>  It would be nice to have some kind of indicator when the task is syncing (for example next to the window title Errands, you can have a spinner)

Yeah, i was thinking about adding that.

> The details panel opens to the left. It would be nice to have this on the right side instead of in the middle.

I'll try to add setting where you can select side of the details panel, but not sure about that. Three panel view is kinda part of the GNOME design.

> When the task is synced/updated, I notice that sometimes the details panel gets closed automatically. 

I've never had it. Maybe it's a bug... Because I close this panel only with toggle button or when trash is opened. Can you describe more about that? When it happens?

**Comment by madhums** [comment]
> > When the task is synced/updated, I notice that sometimes the details panel gets closed automatically.

> I've never had it. Maybe it's a bug... Because I close this panel only with toggle button or when trash is opened. Can you describe more about that? When it happens?

At the end of the video, as soon as I press save and the task is saved, you see the details panel is closed. This happened automatically. Just recorded another video with logs  [Screencast from 2023-12-28 11-49-24.webm](https://github.com/mrvladus/Errands/assets/123815/8fcb5932-f777-4fce-a0ef-1dda6149df6c). Hope it helps.

Thank you for considering all the above feedback, appreciate 🙏🏽

**Comment by mrvladus** [comment]
Closing as the original issue was fixed
