### ISSUE TITLE
today, upcoming and display of tags

### ISSUE THREAD

**Issue by madhums** [mrvladus/Errands#114]
It would be cool to show today, upcoming and a list of tags on the sidebar. Clicking on each of these will show the respective tasks. This would be very helpful in planning and getting an overview.

**Comment by mrvladus** [comment]
Yes! I planned it for future releases.

**Comment by dangrover** [comment]
I came here to post this request. Congrats on a beautiful and thoughtful app! Would you be open to folks submitting PRs for this sort of feature?

**Comment by mrvladus** [comment]
@dangrover Yes, I'm open to any PR's as long as it follows design of the app and doesn't complicate things :)

**Comment by mrvladus** [comment]
Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)

**Comment by dangrover** [comment]
This is great! Something I noticed, though, is that its "today" doesn't match the one in Todoist -- it doesn't show things that are past due. Is this an intentional design decision?
