### ISSUE TITLE
Google Tasks Integration

### ISSUE THREAD

**Issue by ghassan0** [mrvladus/Errands#122]
Hey, I just saw your app in TWIG. Thanks for developing this app, you did a great job following Gnome's design.

I was hoping I'd be able to use it with Google Tasks. I see that you've added CalDAV support, so I attempted to use `https://www.google.com/calendar/dav/` as the server URL with no luck. Ideally, Errands would use my Google account from Gnome Online Accounts.

**Comment by mrvladus** [comment]
Hi! I tested Google Calendar CalDAV and it seems that it does not let to create new calendars / task lists or change existing events. The only thing I could get is calendars and events that I created in the web app. And another thing is that Google Tasks does not use CalDAV. It is a known problem with Google not working with CalDAV properly.

**Comment by mariolinux** [comment]
I can access Google Tasks via the gnome-shell extension _Task Widget_: https://extensions.gnome.org/extension/3569/task-widget/ (or https://gitlab.com/jmiskinis/gnome-shell-extension-task-widget). It integrates with Gnome Online Accounts and I believe it uses _gi://EDataServer_, _gi://ECal_, _gi://ICalGLib_. Could this be a way to integrate Errands with Gnome Online Accounts?

**Comment by ghassan0** [comment]
I just checked and [Endeavor](https://gitlab.gnome.org/World/Endeavour) is able to use GOA, so it is possible. Unfortunately, I'm not a fan of how Endeavor deals with the tasks from Google since I couldn't figure out how to set them as the default task list instead of local tasks.

**Comment by antrmn** [comment]
I'm pretty sure Endeavour's developers aren't having a fun time having to deal with Evolution Data Server. In my opinion, It is better to strive away from such a burden.

**Comment by Beryesa** [comment]
Wouldn't integration with Gnome online accounts provide Google caldav?

**Comment by mrvladus** [comment]
@Beryesa Nope. As it was sad earlier Endeavour is using Evolution data server for this, and I'm not ready to go this rabbit hole :)

**Comment by fastrizwaan** [comment]
https://github.com/Merrit/adventure_list syncs with google caldav, can't we use that?

https://flathub.org/apps/codes.merritt.adventurelist

**Comment by mrvladus** [comment]
I decided not to implement Google sync for now.
