### ISSUE TITLE
Packaging for Nix

### ISSUE THREAD

**Issue by keirlawson** [mrvladus/Errands#127]
I've requested that this application be packaged for Nix/NixOS https://github.com/NixOS/nixpkgs/issues/277705 however it has been pointed out that in the readme the author indicates that they would prefer this application not be packaged outside of flatpak.  So just wanted to check if the preference is not to have it packaged in which case I will close the Nix issue.

**Comment by mrvladus** [comment]
@keirlawson Hi! Thank you for asking me first! I'm really prefer this app is not to be packaged in other formats, because I target GNOME flatpak platform SDK and don't wanna fix some dependencies issues that might occur with other formats.

**Comment by keirlawson** [comment]
okidoke
