### ISSUE TITLE
Open details panel to the right

### ISSUE THREAD

**Issue by madhums** [mrvladus/Errands#129]
The talks detail panel opens in the middle. This is somewhat unintuitive. Would be nice if it can be opened to the right following the information hierarchy (Task list -> Task -> Task detail)

_From discussion https://github.com/mrvladus/Errands/issues/113#issuecomment-1871007431_

**Comment by Sesivany** [comment]
I second this. Opening the details panel in the middle sort of rubs me the wrong way. I think the layout "task lists->selected task list->selected task" feels much more natural.

**Comment by mrvladus** [comment]
Added preference in [45.1.5](https://github.com/mrvladus/Errands/releases/tag/45.1.5)

**Comment by madhums** [comment]
Thank you <3
