### ISSUE TITLE
Nextcloud synchronization doesn't work

### ISSUE THREAD

**Issue by quentinDupont** [mrvladus/Errands#133]
Hello and thanks for all the work
I discover this awesome software which seems very interesting for its synchronization feature with Nextcloud.

I set the parameter Netxcloud, test with succcess the connection and try to synchronise new list but nothing happens.
Log doesn't show anything :

```
[DEBUG] Loading tasks for 'f48ce1ce-7cd1-46d5-a69c-62a84144806e'
[INFO] Add task: 8da7ac77-98af-4562-8f60-4c2e5779ff08
[DEBUG] Loading tasks for '9dd4b667-e9fc-49e4-ba26-ed0d03b636e8'
[DEBUG] Loading tasks for 'dc121fc7-ed20-4901-9ecf-8e4c78625312'
[DEBUG] Loading tasks for 'b176e369-f3c9-4897-a16c-b20a9bd1990e'
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
```

I don't know how to be more precise.
On Nextcloud app Tasks, I don't see my new lists created on Errands, neither I see my Nextcloud list on Errands :shrug: 

Thanks in advance :)

**Comment by mrvladus** [comment]
Hi! It is strange that it tries to create 3 new lists with same uuid... Can you try to disable sync, reload the app, turn sync back on and reload app again?

**Comment by quentinDupont** [comment]
> Hi! It is strange that it tries to create 3 new lists with same uuid... Can you try to disable sync, reload the app, turn sync back on and reload app again?

I just follow your steps, it connects to my Nextcloud but same results after

[```
DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
[INFO] Sync: Initialize sync provider
[INFO] Sync: Initialize Nextcloud sync provider
[DEBUG] Sync: Checking credentials
[DEBUG] Sync: Checking URL
[DEBUG] Sync: URL is set to http://nuage.xxxx.xxxx/remote.php/dav/
[DEBUG] Sync: Attempting connection
[INFO] Sync: Connected to Nextcloud server at 'http://nuage.xxxx.xxxx/remote.php/dav/'
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Create list on remote 539399d0-0af9-4f4a-b114-615d0f3204f2
```

**Comment by mrvladus** [comment]
You can try to delete database file at `~/.var/app/io.github.mrvladus.List/data/errands/data.db` but make backup first.

**Comment by quentinDupont** [comment]
It works ! I didn't have any datas so no backup, i start again
But I also made an other change : add **https** instead of **http** for the Nextcloud URL
