### ISSUE TITLE
Have preset time options

### ISSUE THREAD

**Issue by Sesivany** [mrvladus/Errands#134]
When I need to set a time for a task, it's not very handy to always type an exact time. Would it be possible to introduce several preset times for the day like OpenTasks.org for Android has (see the screenshot)? I (and I suppose many other users) would be OK with picking from like 4 times a day (morning, noon, afternoon, evening) and it's much easier to just click one of them than typing it every time. And there can always be an option to type a different time if needed.
In OpenTasks, you can configure the preset times, but that's not a must IMO.
![photo_2024-01-05_16-29-25](https://github.com/mrvladus/Errands/assets/4135539/8b410b85-6e98-4ca3-b1a7-591c8358ea6a)

**Comment by mrvladus** [comment]
Good idea! I'll add them.

**Comment by mrvladus** [comment]
Added in [45.1.4](https://github.com/mrvladus/Errands/releases/tag/45.1.4)
