### ISSUE TITLE
Include emojis or colors to further customize task lists

### ISSUE THREAD

**Issue by d4r1us-drk** [mrvladus/Errands#135]
It would be nice if the user had the choice for customizing task lists further, not only just a name, but also an emoji or a color (interchangable). Although I don't know if this would be interoperable with CalDav and Nextcloud. I remember Nextcloud having these features, so maybe it's possible to sync these things with the CalDav protocol. A reference implementation would be Planify (another GTK4 + libadwaita To-Do app):

![image](https://github.com/mrvladus/Errands/assets/131416536/7581a93c-6c09-4b3f-bc19-aa654b12906f)

![image](https://github.com/mrvladus/Errands/assets/131416536/aca89145-3397-4b00-914b-e9a9b3ca02aa)

![image](https://github.com/mrvladus/Errands/assets/131416536/12c9d9d7-919c-4bdd-bc67-fbd758822561)

**Comment by mrvladus** [comment]
I'm not going to emoji's, but list's accent color is planned feature, because it's implemented in a few caldav providers, including nextcloud.

**Comment by benmordecai** [comment]
Worth noting that it is possible to add emojis already by using your system emoji picker and including it in the name of notebooks or tasks

**Comment by d4r1us-drk** [comment]
That's true, thanks for pointing that out. I didn't remember GNOME had an emoji picker until now.
