### ISSUE TITLE
Percentage completion update & Progress bar

### ISSUE THREAD

**Issue by wada3n** [mrvladus/Errands#140]
Hi,

Any chance to add:

- **Percentage completion for parent tasks:** When a child task completes, the percentage completion for the parent task should be updated. This would make it easier to track the overall progress of a task list.
- **Progress bar for parent tasks:** A progress bar should be displayed for each parent task. This would provide a visual representation of the task's progress.

I believe these features would be valuable additions to the Errands app. 

Thanks for your consideration.

**Comment by mrvladus** [comment]
Hi! Yes, I was planning to add this in future releases :)

**Comment by benmordecai** [comment]
Glad to see this, I was considering making the request also

**Comment by mrvladus** [comment]
Added progress bar in [45.1.8](https://github.com/mrvladus/Errands/releases/tag/45.1.8)

**Comment by wada3n** [comment]
Hi @mrvladus ,

I noticed a new issue after the progress bar fix:

The "Complete %" indicator doesn't change When I complete a task without subtasks,
