### ISSUE TITLE
Nextcloud sync assumes http instead of https from nextcloud url without specified protocol

### ISSUE THREAD

**Issue by benmordecai** [mrvladus/Errands#141]
I am not sure it this should be considered a bug or not but I am reporting so the developer can make the call, but I found it confusing and initially assumed that Errands does not work.

Upon a fresh install of Errands from Flatpak, I set up the Nextcloud sync with credentials like follows:
URL: myurl.com/nextcloud
user: ben
password: ***********

Then I tested the connection and it said it succeeded. Then I manually triggered a fetch and nothing happened. It was unclear the sync was failing until I launched errands from the command line to look at the logs and found that it was failing to find the dav service as http://myurl.com/nextcloud - note the lack of https. I went back to sync config and saw that it had expanded the url automatically in the config menu with http://myurl.com/nextcloud. Once I changed the sync config to https, it worked automatically. 

My instance of Nextcloud forwards requests from http to https so it is legitimate to see a connection on http that succeeded, but without the redirection to https it will fail. 

Since Nextcloud itself strongly recommends https, errands could set up base urls to default to https unless the user explicitly enters http:// and this would prevent a problem where errands gets blamed for silently failing to sync due to a misconfiguration.

**Comment by mrvladus** [comment]
I'll add `https` check first. Thanks!
