### ISSUE TITLE
Add "primary action" preference

### ISSUE THREAD

**Issue by david-swift** [mrvladus/Errands#143]
Hi,

I don't often edit a task's properties, but I quite often toggle the expansion of sub-tasks. It would be great if it were possible to change the behavior of clicking the task in the app's settings. The current implementation (clicking on the task toggles the details view, there's a button for toggling the subtasks' visibility) could be the default state, while changing the "primary action" to expanding the sub-tasks would result in a UI similar to this one:

![Screenshot from 2024-01-07 09-08-40](https://github.com/mrvladus/Errands/assets/106754840/fe2a2262-29a9-4056-b2ae-99fc78d4e619)

I think the button for the subtasks should stay there to indicate that this action is possible.

What do you think about it? Thanks in advance!

**Comment by mrvladus** [comment]
I really don't wanna add more buttons to the task row, I like current clean look. But maybe we can add details button besides "Add new sub-task" entry when task is expanded?

**Comment by david-swift** [comment]
Yes, I definitely prefer the current clean look as well and wasn't too happy about adding more buttons to the task row. Is that what you thought of?

![image](https://github.com/mrvladus/Errands/assets/106754840/ad9c10f1-a959-4319-9003-df1114c22bce)

I prefer this design over my initial idea. Thanks for the suggestion! Would you in general support the idea of being able to change the "primary action" (or how we'd call it)? If yes, I could work on it.

**Comment by mrvladus** [comment]
Yes, we can implement this.

**Comment by mrvladus** [comment]
Added in [45.1.5](https://github.com/mrvladus/Errands/releases/tag/45.1.5)
