### ISSUE TITLE
[Feature Request] Third option to close sidebar

### ISSUE THREAD

**Issue by Natetronn** [mrvladus/Errands#145]
Currently, if one clicks on a task, the sidebar opens. To close it, we have two options (that I'm aware of). The first is to click on the task again. The second is via the "Toggle Sidebar" icon. 

A third option could trigger when clicking on any empty space to either side of the tasks:

![image](https://github.com/mrvladus/Errands/assets/582149/58a2ceb4-896a-43c7-96c8-5b272b94d456)

The space between the sidebar and the tasks, in particular, would be a nice quality of life addition.

Thanks!

**Comment by mrvladus** [comment]
I was thinking about that. We are used to this behavior in many apps, probably it's a good idea to add this here too. I'll try to add this.

**Comment by Natetronn** [comment]
> I was thinking about that. We are used to this behavior in many apps, probably it's a good idea to add this here too. I'll try to add this.

Yes, exactly. This is often how offcanvas nav/menus and drawers function on the web and mobile devices. For example:

https://tw-elements.com/docs/standard/navigation/offcanvas/

**Comment by mrvladus** [comment]
Implemented with f07efc944b41628627f1288c06c9a0a9a89a82dc. Will be in the next release.

**Comment by Natetronn** [comment]
Thank you!
