### ISSUE TITLE
Delete Completed Tasks is grayed out when there are existing completed tasks that were marked complete with another client. 

### ISSUE THREAD

**Issue by benmordecai** [mrvladus/Errands#146]
It appears that Errands is checking to see if at least one task has been completed from within Errands in order to allow you to delete completed tasks, so if you have existing completed tasks from the web interface of Nextcloud tasks, Errands will not recognize that they can be deleted until you first toggle at least one task as uncompleted then completed again.

**Comment by mrvladus** [comment]
Yep, can confirm. Luckily, it's an easy fix :)

**Comment by mrvladus** [comment]
Fixed in c77d87d9873f830b416c137149e8c6975f113f1d

**Comment by mrvladus** [comment]
Fixed in [45.1.5](https://github.com/mrvladus/Errands/releases/tag/45.1.5)
