### ISSUE TITLE
Microsoft To-do Caldav integration?

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/Errands#148]
Hi, would it be possible to sync with microsoft todo?

Rememberance/Reminders work with Microsoft Todo and it is a python project https://github.com/remindersdevs/Reminders

**Comment by fastrizwaan** [comment]
but still the best would be to have google task integration,

https://flathub.org/apps/codes.merritt.adventurelist integrates google's tasks. please look into it also.

In the mean time are there any free caldev servers to be used by us?

**Comment by mrvladus** [comment]
Microsoft integration is not planned
