### ISSUE TITLE
Markdown support in task note

### ISSUE THREAD

**Issue by wada3n** [mrvladus/Errands#154]
I think adding Markdown support to Task notes would be a great addition to the app.

**Comment by mrvladus** [comment]
Not sure about that, I think it's not nessesary.

**Comment by wada3n** [comment]
Hi @mrvladus,

I think markdown would make it much easier to create and format task notes. It allows to add style and structure:

- Add headings and subheadings to organize notes
- Add links to other resources
- Use bold, italics, and strikethrough to emphasize important information

![hero-markdown-guide p128](https://github.com/mrvladus/Errands/assets/13304792/1ce73126-3bf8-4d85-b807-2b7c49c6fd4f)

I understand that this might not be a high priority for you, but I think it would be a valuable addition to the app. 
If you're not interested in adding it, that's fine. I can just close this GitHub issue.

Thanks for your time and consideration.

**Comment by mrvladus** [comment]
Maybe I'll add this in the future. I just need to implement markup parser for GtkTextView

**Comment by mrvladus** [comment]
Added markdown syntax highlighting in [45.1.8](https://github.com/mrvladus/Errands/releases/tag/45.1.8)
