### ISSUE TITLE
Adding Attachments To Task

### ISSUE THREAD

**Issue by wada3n** [mrvladus/Errands#155]
Hi,
I would like to request the ability to attach files and images to Task properties. 
This would be a great way to store additional information about a task, such as screenshots, documentation, or reference materials.

**Comment by mrvladus** [comment]
I can do that, probably under tags section in the detais panel, but it won't be synced, and only local files will be supported

**Comment by jeena** [comment]
Would you hide this possibility on lists which have a sync backend? Otherwise it will be very confusing for people that they added an attachment and it is not propagated to other clients or instances.

**Comment by mrvladus** [comment]
@jeena I can hide them when sync is enabled or just say "Local Attachments"

**Comment by mat-l** [comment]
Inline images would be a killer feature, then I could drop Logseq :D

**Comment by mrvladus** [comment]
Added local attachments in c71219e3ba3ded4cf8c82f602e18df29a3125297. Will be in 46.1 release.
