### ISSUE TITLE
Visibly mark selected colour

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#159]
Hi, it would be nice to have a border to mark the currently selected color of a task.
![grafik](https://github.com/mrvladus/Errands/assets/43520007/4e9ca9ff-f6b2-4918-837a-7aa9f3f3af37)

**Comment by mrvladus** [comment]
Yeah, I should add this :)

**Comment by mrvladus** [comment]
Reworked color switch, now it will show checkmark on the selected color. Will be in next release.
