### ISSUE TITLE
Bug: Can't choose "preselected" day

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#161]
Hi, I noticed a bug in the date picker. When you open it, a day appears to be pre-selected (marked in blue), even though it is not actually selected. The problem is that you cannot click on it and really select that particular day. Any other day works.

 **In the example of the screenshot below, I was not able to simply click on the 14th of January (which is today) to schedule the task.**

Also, the first time you open the date picker on any task, the selected day will appear as the current day. Once you have selected a date and then clear that selection, the blue marker remains on the previously selected day. I think it would make more sense to "clear" this as well, and also reset the marker to the current day.

![grafik](https://github.com/mrvladus/Errands/assets/43520007/09f12740-a688-496b-b41c-18635755cbd7)

**Comment by mrvladus** [comment]
It's a GTK thing, I can't un-select day in GtkCalendar, I hate it too, but I'm not ready to create custom calendar widget :) Maybe you can file this to [GTK repo](https://gitlab.gnome.org/GNOME/gtk)?

**Comment by Julian4711** [comment]
I'm not a developer and don't really have a clue, but there is this: [Gtk>Calendar>unmark_day](https://docs.gtk.org/gtk4/method.Calendar.unmark_day.html)

**Comment by mrvladus** [comment]
@Julian4711 yeah... Logically, it should do what it said, but nope, it doesn't un-select default day.

**Comment by Julian4711** [comment]
Also https://docs.gtk.org/gtk4/method.Calendar.clear_marks.html.

> @Julian4711 yeah... Logically, it should do what it said, but nope, it doesn't un-select default day.

Ok, thanks, then there is probably not much you can do about it.

**Comment by mrvladus** [comment]
@Julian4711 because of that behaviour I made "Today" button
