### ISSUE TITLE
Bug: Apostroph in CalDav calendar name throws error

### ISSUE THREAD

**Issue by jeena** [mrvladus/Errands#171]
I connected to my Radicale CalDav server and one of my calendars had the name "Jeena's", this lead to this error in the log:

`[ERROR] Data: near "s": syntax error`

and this specific list did not show up, so I thought Errands only can deal with one list which was strange because the UI is prepared to have a list of Lists in the sidebar.

Once I changed the name from "Jeena's" to "Jeenas" and resynced, everything worked fine.

**Comment by mrvladus** [comment]
Fixed in a1a8bf016c526cafb7561213a99ca060b2b08f15. Will be available in the next release.

**Comment by mrvladus** [comment]
Added in [45.1.7](https://github.com/mrvladus/Errands/releases/tag/45.1.7)
