### ISSUE TITLE
Option to automatically save details

### ISSUE THREAD

**Issue by jeena** [mrvladus/Errands#172]
I was just happily adding important details to many of my tasks and subtasks just afterwards to realize that nothing has been saved and all the details were gone.

When I create a new task I don't need to press save, neither for a subtask, so I didn't expect that I should press the save button which is at the top of the details (I didn't realize it was there because I was concentrating on notes, tags, etc. at the bottom). Every time I switched to add more details to another task all my details dissapeared without any warning.

I'm not sure why the save button is there, I think once you change to a different task the details should be automatically saved, it's almost never that I want to cancel changes which I'm making.

Other applications either save it automatically or have the details as a modal dialog (see GNOME Calendar) or just save all the changes which are made inline automatically once someone leaves the textarea.

**Comment by Sesivany** [comment]
I was just going to file a ticket about it. IMHO the Save button is unnecessary, or even confusing. AFAIK the GNOME guidelines have said for many years that the data should be saved as it is typed in. Users are used to it and this confuses them, myself included.

**Comment by mrvladus** [comment]
Added in [45.1.7](https://github.com/mrvladus/Errands/releases/tag/45.1.7)
