### ISSUE TITLE
Drag and drop tasks between lists

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#176]
Hi, I'd like to be able to move tasks between different task lists by dragging and dropping them onto the new list.

**Comment by mrvladus** [comment]
@Julian4711 I already added that. Or do you mean move tasks from one list to specific position in another?

**Comment by Julian4711** [comment]
You are right :D
I probably was on an older version when I last checked that. Thank you!

**Comment by mrvladus** [comment]
I'll add drag to a specific position in the next major release too

**Comment by mrvladus** [comment]
I just found a bug with this. please don't use this for now

**Comment by mrvladus** [comment]
Removed in [45.1.7](https://github.com/mrvladus/Errands/releases/tag/45.1.7) for now, will add in major release

**Comment by mrvladus** [comment]
Added fully featured in [45.1.8](https://github.com/mrvladus/Errands/releases/tag/45.1.8)
