### ISSUE TITLE
New Tasks position

### ISSUE THREAD

**Issue by mosK1T0** [mrvladus/Errands#179]
I don't know how Errands sorts tasks but all open tasks are at the bottom. It would be way more logical, at least in my opinion to show them first so I can see them right away. #

**Comment by mrvladus** [comment]
@mosK1T0 by "open" tasks you mean uncompleted?

**Comment by mrvladus** [comment]
If you mean where to add new tasks - on top or bottom, then it will be added in future versions.

**Comment by mrvladus** [comment]
Implemented in ba764d0bcec3ffc640c947be2b18bfa4f481daa4, will be in the next release.

**Comment by mosK1T0** [comment]
I'm sorry I didn't answer. But yes that is exactly what I mean. Thank you for implementing it.
