### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by carlnickel** [mrvladus/Errands#180]
Since last update Errands does not start up at all. What happened?

**Comment by mrvladus** [comment]
Can you paste terminal output?

**Comment by carlnickel** [comment]
Sorry, how can I do that? What command?

Am 24. Januar 2024 16:35:53 MEZ schrieb mrvladus ***@***.***>:

**Comment by mrvladus** [comment]
run in terminal `flatpak run io.github.mrvladus.List`

**Comment by carlnickel** [comment]
okay, it is running since 15 minutes, is this normal? it says:

[DEBUG] Starting Errands 45.1.6
[DEBUG] Initialize GSettings
[DEBUG] Creating actions
[DEBUG] Loading tasks for 'personal'

and then there follows a lot. you want to see all of it, when it is done? :)

**Comment by carlnickel** [comment]
okay, i gave up after one hour and reinstalled the app and removed the starter customized by GNOME Main Menu app. I guess that starter did not work anymore after update, so there was no bug. mistake on my side, sorry for that.
