### ISSUE TITLE
Duplicated tasks after failed drag and drop

### ISSUE THREAD

**Issue by benmordecai** [mrvladus/Errands#181]
Under some conditions, drag and drop to rearrange tasks fails. Typically, this is when you try to scroll while dragging. This causes the drop indicator to remain visible even after letting go of the mouse click and the drop indicator remains visible until the program is exited and restarted.

Upon restart, the task list has duplicate copies of every task. However, this duplication is local to Errands and is not pushed to the server, which still only has one copy. There is no apparent method to make the duplicates go away.

**Comment by benmordecai** [comment]
If you check as complete the duplicate tasks and try to use "Delete All Completed Tasks" the option to Delete All Completed tasks remains grayed out

**Comment by mrvladus** [comment]
@benmordecai When you check task is task duplicate checks too?

**Comment by benmordecai** [comment]
No, the tasks act as distinct tasks that check separately

**Comment by mrvladus** [comment]
@benmordecai can you test the new 45.1.7 version from flathub? I did some stuff with sync, maybe it's fixed now.

**Comment by benmordecai** [comment]
Seems to be fixed, thanks!

**Comment by mrvladus** [comment]
Great! Closing then.
