### ISSUE TITLE
Slow Task upload with CalDav

### ISSUE THREAD

**Issue by iFabse** [mrvladus/Errands#192]
Is it just me or does the upload of tasks take some time? About 5 to 8 sec

**Comment by mrvladus** [comment]
I'm aware that with many tasks and calendars it can be a little slow, it's because it pulls all tasks from server every time. I'm trying to make it sync only changed tasks right now.

**Comment by mrvladus** [comment]
Improved sync speed in [45.1.8](https://github.com/mrvladus/Errands/releases/tag/45.1.8). But the main problem that all calendars fetched every time won't be fixed until I rewrite CalDAV implementation from scratch or python-caldav library will make that possible.
