### ISSUE TITLE
Feature request: The completed task is automatically sent down

### ISSUE THREAD

**Issue by posilya** [mrvladus/Errands#195]
Hi!

Can you please add a setting so that the task you marked completed is automatically moved to the bottom of the list? There is something similar in Apple Notes.

---

And thank you for the app, it's great!

**Comment by madhums** [comment]
Very useful feature!

**Comment by mrvladus** [comment]
Will do! 😄

**Comment by jeena** [comment]
Yes, I feel I'm sorting completed tasks more than I'm doing anything else, that would be a really useful feature.

**Comment by mrvladus** [comment]
Implemented it on `dev` branch, will be available in the next release.
