### ISSUE TITLE
Detail of the task on the right and collapsed property activated

### ISSUE THREAD

**Issue by alainm23** [mrvladus/Errands#199]
Hi, great app, maybe as a suggestion the task view should be on the right side (I think it would feel more natural) and the collapsed pripiedad enabled.

Maybe you could add it as a preference that the user can change it.

![image](https://github.com/mrvladus/Errands/assets/33765137/84eb2eeb-53ac-491b-a7a5-e7d8631b785f)

**Comment by mrvladus** [comment]
How did you done that? How you made sidebar collapsed while list of task-lists on the left is showing? I can't even replicate this layout on screenshot 😃 Can you record video?

**Comment by alainm23** [comment]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.4/class.OverlaySplitView.html

```
Adw.OverlaySplitView.collapsed = true;
Adw.OverlaySplitView.sidebar_position = Gtk.PackType.END;
```

[Grabación de pantalla desde 2024-02-07 08-51-39.webm](https://github.com/mrvladus/Errands/assets/33765137/ba632840-cce9-427f-bba1-aded86b43468)

**Comment by mrvladus** [comment]
There is already setting for selecting side of the details panel.

**Comment by BeatLink** [comment]
could the right side be set as default?

**Comment by mrvladus** [comment]
Sidebar is replaced with toolbar in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)
