### ISSUE TITLE
Daily tasks check is all or non

### ISSUE THREAD

**Issue by shetozz** [mrvladus/Errands#204]
I have a CalDAV server that I imported tasks from to Errands, when I mark a task as done, it counts it as done forever and removes all the future listings of the task.

**Expected behavior**
it should mark only today's task as done.

**Comment by mrvladus** [comment]
What CalDAV server do you use? Nextcloud or something different?

**Comment by shetozz** [comment]
A local one with Radicale

**Comment by mrvladus** [comment]
It's probably because Errands does not support recurrent tasks yet. It will in next releases.

**Comment by mrvladus** [comment]
Closing as it will be worked on for #90
