### ISSUE TITLE
Design broken on KDE Wayland; rows are tiny, text squashed

### ISSUE THREAD

**Issue by kekkoudesu** [mrvladus/Errands#208]
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.4-arch1-1 (64-bit)
Graphics Platform: Wayland

OS: Arch Linux

Output of `flatpak list`:

```
Errands                                           io.github.mrvladus.List                                  45.1.9                  stable                  system
```

What Errands looks like for me:
![image](https://github.com/mrvladus/Errands/assets/88186997/4ec42fc0-0929-40cd-b150-4d3b054829bb)

It's not usable.

**Comment by mrvladus** [comment]
Does other libadwaita apps behave the same?

**Comment by kekkoudesu** [comment]
Yes, like [Done](https://flathub.org/apps/dev.edfloreshz.Done).

**Comment by kekkoudesu** [comment]
Yep. Most of the task is completely cut off too in "Done".

**Comment by mrvladus** [comment]
I guess it's archlinux and KDE bug, probably something to do with fontconfig, or maybe some font packages are not installed.

**Comment by kekkoudesu** [comment]
Do you know what fonts I should try installing?

I've tested Errands on another Arch computer running GNOME and it looks fine. Done also looks fine on (yet another, different) Arch computer running GNOME. So it seems to happen purely on KDE.

**Comment by kekkoudesu** [comment]
I just built the [AUR package](https://aur.archlinux.org/packages/errands) and it's completely fine on KDE.

![image](https://github.com/mrvladus/Errands/assets/88186997/dc39e9d6-e583-461e-93b8-529c0b323134)

Seems to be a Flatpak bug.

**Comment by mrvladus** [comment]
Probably related to https://github.com/flatpak/flatpak/issues/2861

**Comment by kekkoudesu** [comment]
I tried installing `gnome-settings-daemon` (which brought `gcr` along for the ride), but the Flatpak version still doesn't work.

For now I've copied all my tasks to the AUR version which is working great.

**Comment by kekkoudesu** [comment]
I noticed that when I run the AUR version (and *only* the AUR version; it's not like this for the Flatpak version), I get:

```
[DEBUG] Starting Errands 45.1.8

(errands:36272): Gtk-WARNING **: 10:57:25.515: Unknown key gtk-modules in /home/user/.config/gtk-4.0/settings.ini
[DEBUG] Creating actions
[DEBUG] Initialize GSettings
[DEBUG] Task list d3e845aa-ca83-4287-af8d-59edbb7c7b26: Update UI
```

Despite this, I don't see any issues with the interface.

**Comment by mrvladus** [comment]
Closing as not related to Errands
