### ISSUE TITLE
Problems with CalDav-Synchronisation

### ISSUE THREAD

**Issue by CodingTurtle2** [mrvladus/Errands#209]
(I use ConsoleH, which provides CalDav, if that's important)
Changes are only applied if I made them on ConsoleH, but not on the CalDav server if I made them with Errands.
So I think, it does not synchronize with the CalDav-Server.
For Example:
  - I delete a task on Errands and after I synchronised my task, it came back
[screen recording (video)](https://github.com/mrvladus/Errands/assets/104490184/7cce2f3a-f51b-4b0e-8e50-dc19d209f0a3)
  - When I create a new task or check an old task, it does not show up on ConsoleH

**Comment by mrvladus** [comment]
Can you copy terminal output of `flatpak run io.github.mrvladus.List`?

**Comment by mrvladus** [comment]
Yeah, I think so too. Probably ConsoleH doesn't follow CalDAV protocol completely or the changed it significantly.
