### ISSUE TITLE
[Feature request] Show due date on task list and sort by due date by default

### ISSUE THREAD

**Issue by abbluiz** [mrvladus/Errands#216]
**Is your feature request related to a problem? Please describe.**
Not exactly. Just a missing feature. I have to click on the task information to see the due date.

**Describe the solution you'd like**
I would like to know when the tasks are due just by looking at the task list, so the list would show the due date/hours and it should be sorted by due date by default (ascending order -- tasks that have to be completed earlier show up first).

**Describe alternatives you've considered**
_No alternatives considered._

**Additional context**
_No additional context._

**Comment by mrvladus** [comment]
It will be shown in the next major release

**Comment by abbluiz** [comment]
> It will be shown in the next major release

Great news. Thank you!

**Comment by mrvladus** [comment]
Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)
