### ISSUE TITLE
[BUG] Wrong version number

### ISSUE THREAD

**Issue by shetozz** [mrvladus/Errands#220]
**Describe the bug**
The last release on GitHub and Flathub is 45.1.9, but the app reports 45.1.8 for some reason.

**To Reproduce**
1. Install Errands from flathub
2. Launch it and go to `about`

**Expected behavior**
It should report `45.1.9`

**Screenshots and screencasts**
![image](https://github.com/mrvladus/Errands/assets/93838524/108a2f0b-6010-48d6-999b-a8b1e01f8db6)

![image](https://github.com/mrvladus/Errands/assets/93838524/7a841fcf-7e2e-4e52-b71c-e30384105991)

**OS info:**
- Distro: Fedora 39 workstation edition.
- Desktop Environment: GNOME
- Using latest version from Flathub: yes, it's installed only for the user.

**Additional context**
in the screenshot with the terminal output, I included an update attempt to show I'm on the latest release.

**Comment by mrvladus** [comment]
Fixed on `dev` branch.
