### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by The-Rev-Dwanye** [mrvladus/Errands#225]
**Describe the bug**

**To Reproduce**
1. open errands

**Expected behavior**
I would expect the application to open with the correct configuration to allow display of the center,

**Screenshots and screencasts**
![errands_manjaro_kde_wayland](https://github.com/mrvladus/Errands/assets/114014125/d1fd6ce6-9d2c-47a9-aba0-b03811f313b5)
![errands_manjaro_kde_x11](https://github.com/mrvladus/Errands/assets/114014125/49f6f074-6a89-469f-8cd9-f980b9562b44)

**OS info:**
- Distro: Manjaro
- Desktop Enviroment: KDE Plasma Wayland
- Using latest version from Flathub: yes 

**Additional context**
as you can see, when I run plasma with x11 the application runs as expected. Under wayland it does not.

**Comment by mrvladus** [comment]
Have you tried running other libadwaita apps? Does they behave the same, or it is only Errands?

**Comment by The-Rev-Dwanye** [comment]
Thank you for your quick response. I have not tried other 'libadwaita'. I just saw that errands wasn't acting nice and switched to x11 and noticed that errands ui was as expected. I'm running errands on an omen laptop with amd ryzen with Nvidia GPU.

Thanks again.

Sent from Proton Mail mobile

0
-------- Original Message --------
