### ISSUE TITLE
[Feature request] Show all tasks

### ISSUE THREAD

**Issue by saltecaramel** [mrvladus/Errands#233]
A button to show all the tasks from the different tasks lists. In the "all" view it should also be segmented by the different list. 

Alternatively, a number could be added next to the lists on the left side. The problem I face is that I have to manually click through all the lists to see which one has tasks and which don't.

**Comment by mrvladus** [comment]
I already added number of tasks to the sidebar task row on the `dev` branch, it'll be available in the next update.

**Comment by mrvladus** [comment]
Added number of tasks badge for task lists in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)
