### ISSUE TITLE
[BUG] nextcloud Sync fails for one specific task list only

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#235]
**Describe the bug**
Hi, I am having a problem synchronising or loading a specific to-do list from my Nextcloud instance. In general the sync works, but with this one list it fails. Here is what the log says about this list:
```
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Getting tasks for aufgaben
[DEBUG] Sync: Delete orphaned task: 1572684427854887556
[ERROR] Sync: Can't get tasks from remote. NotFoundError at '1572684427854887556 not found on server', reason no reason
[DEBUG] Sync: Copy list from remote aufgaben
[DEBUG] Data: Create 'aufgaben' list
```

The list contains 5 tasks. There are no child or parent tasks for any of them. I don't know what the log message could be referring to. In fact, every single one of these tasks has an empty "RELATED-TO" entry. I have already deleted the Errands SQLite DB and re-imported it completely. Unfortunately, it makes no difference. What else could I do?

**To Reproduce**
1. Delete the Errands SQLite DB at ~/.var/app/io.github.mrvladus.List/data/errands/
2. Start Errands
3. Wait for Sync to be finished and DB to be created again
4. Compare with Nextcloud: All lists except one are imported. The log shows the above error. 

**Expected behavior**
All lists are imported correctly as they appear on nextcloud.

**OS info:**
- Distro: Manjaro
- Desktop Enviroment: Gnome
- Using latest version from Flathub: yes

**Comment by mrvladus** [comment]
It may be happening if one of the tasks has `parent` set, but parent task is not exists. Nextcloud sometimes bugs with this, you can try to move tasks on nextcloud  from their parents to be toplevel and then try to sync again.

**Comment by mrvladus** [comment]
I've made so Errands now will detect orphaned tasks and remove their parent data, so they will become top-level tasks. Now you don't have to use different apps for this problem :)

**Comment by Julian4711** [comment]
great news. when will it arrive in flathub? I sometimes peek at all the improvements you do in the dev branch. Would really like to see them in action ;)

**Comment by mrvladus** [comment]
@Julian4711 I just need to fix some Drag'n'Drop bugs and I will release it.

**Comment by mrvladus** [comment]
Added in 46.0 release.
