### ISSUE TITLE
Refine colors in dark mode

### ISSUE THREAD

**Issue by M00NJ** [mrvladus/Errands#243]
In light mode the available task colors look really nice, but in dark mode not so much. `Orange` is almost brown, `Yellow` has a green tint and `Red` is very dark. In general the colors are a bit over saturated if you ask me. I think this is because the colors are not fully opaque, so the background color comes through. This doesn't affect the colors in light mode since the background is white, but in dark mode the colors are changed.

|Light|Dark|
|---|---|
|![Light](https://github.com/mrvladus/Errands/assets/82398591/5dc71ee2-b134-48c3-aedc-934d5b3ea803)|![Dark](https://github.com/mrvladus/Errands/assets/82398591/1f8056d0-fda9-4047-8f24-0e90092e9c06)|

**Comment by mrvladus** [comment]
How is this looking?
![Снимок экрана от 2024-04-29 19-22-33](https://github.com/mrvladus/Errands/assets/64690334/3ae92f5a-34a2-4669-8452-d5990cd43554)

**Comment by M00NJ** [comment]
Wow, that was fast. Yes, this looks much better. Thank you!

**Comment by mrvladus** [comment]
Cahnged in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)
