### ISSUE TITLE
Use rightclick on sidebar items like Nautilus

### ISSUE THREAD

**Issue by M00NJ** [mrvladus/Errands#246]
This is just a small ui tweak suggestion. I think the ui would look cleaner if the three dot icon on sidebar items was removed and the popup would just appear on right-click, like in Nautilus. 
|Errands|Nautilus|
|---|---|
|![Screenshot from 2024-05-02 11-10-33](https://github.com/mrvladus/Errands/assets/82398591/8ec2b225-c741-4559-9a2a-2ac74524c31e)|![Screenshot from 2024-05-02 11-11-21](https://github.com/mrvladus/Errands/assets/82398591/dd4b2876-cb0a-4246-ac55-329b0169dc15)|

Btw great work on the new release! Errands feels more polished and thought out now with the double sidebar gone and the new categories are super useful :heart:

**Comment by mrvladus** [comment]
Can close this now, will be in the next update.
