### ISSUE TITLE
errands does not start anymore

### ISSUE THREAD

**Issue by eifargotof** [mrvladus/Errands#252]
hi,
for a cpuple of days, errands does not start any more on my main computer. on my second machine, it ist still working. 
both machines are running fedora 39 + 40. 
below i attached the putpunt of the logfile:

09:26:24 errands: IndexError: list index out of range
09:26:24 errands: IndexError: list index out of range
09:26:24 errands:                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
09:26:24 errands:     list_dict = [lst for lst in lists_dicts if lst.uid == task_dict.list_uid][0]
09:26:24 errands:   File "/app/share/errands/errands/widgets/trash/trash.py", line 138, in update_ui
09:26:24 errands:     State.trash_page.update_ui()
09:26:24 errands:   File "/app/share/errands/errands/widgets/trash/trash_sidebar_row.py", line 84, in update_ui
09:26:24 errands:     State.trash_sidebar_row.update_ui()
09:26:24 errands:   File "/app/share/errands/errands/widgets/window.py", line 123, in __finish_load
09:26:24 errands:     self.__finish_load()
09:26:24 errands:   File "/app/share/errands/errands/widgets/window.py", line 42, in __init__
09:26:24 errands:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:26:24 errands:     State.main_window = Window(application=State.application)
09:26:24 errands:   File "/app/share/errands/errands/application.py", line 84, in do_activate
09:26:24 errands: Traceback (most recent call last):
09:26:23 errands: IndexError: list index out of range
09:26:23 errands:                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
09:26:23 errands:     list_dict = [lst for lst in lists_dicts if lst.uid == task_dict.list_uid][0]
09:26:23 errands:   File "/app/share/errands/errands/widgets/trash/trash.py", line 138, in update_ui
09:26:23 errands:     State.trash_page.update_ui()
09:26:23 errands:   File "/app/share/errands/errands/widgets/trash/trash_sidebar_row.py", line 84, in update_ui
09:26:23 errands:     State.trash_sidebar_row.update_ui()
09:26:23 errands:   File "/app/share/errands/errands/widgets/window.py", line 123, in __finish_load
09:26:23 errands:     self.__finish_load()
09:26:23 errands:   File "/app/share/errands/errands/widgets/window.py", line 42, in __init__
09:26:23 errands:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:26:23 errands:     State.main_window = Window(application=State.application)
09:26:23 errands:   File "/app/share/errands/errands/application.py", line 78, in do_startup
09:26:23 errands: Traceback (most recent call last):

**Comment by mrvladus** [comment]
I think, I fixed it in [46.0.2](https://github.com/mrvladus/Errands/releases/tag/46.0.2). When update will arrive can you test it? After update you will need to reboot or re-login.

**Comment by mosK1T0** [comment]
I had the same issue and it's working fine after the update and reboot.

**Comment by eifargotof** [comment]
it is working again - thank you very much! :)


Am Samstag, dem 04.05.2024 um 09:07 -0700 schrieb mrvladus:
