### ISSUE TITLE
Application no longer opens

### ISSUE THREAD

**Issue by rightpad** [mrvladus/Errands#258]
I've been using the application every now and then, but after an update it no longer works. 

Possibly related to #252, but I don't receive any log output so I'm not sure.

I'm on Fedora 40 (KDE Spin). I've updated via `flatpak update` and applied all system upgrades via my system's package manager. I tried to find any log files in `~/.var/app/io.github.mrvladus.List`, but only some bare directories are created (cache, config, data). Unfortunately, running via `flatpak run io.github.mrvladus.List` doesn't produce any output at all. Is there some environment variable I need to set or something similar in order to get debug output? Also, thank you very much for your work on the application and the help!

`flatpak info io.github.mrvladus.List` output:

```
Errands - Manage your tasks

          ID: io.github.mrvladus.List
         Ref: app/io.github.mrvladus.List/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 46.0.3
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 21.1 MB
     Runtime: org.gnome.Platform/x86_64/46
         Sdk: org.gnome.Sdk/x86_64/46

      Commit: dd8a1c9d368c197d3442b07e0669fab0dd4d0c60f1136ae9531d8a2ee706a394
      Parent: 7c097f3ee5e35249283c5992ca7f936c29674bb8edc62c250b9747fd1efa1f76
     Subject: Update io.github.mrvladus.List.json (6cfd47e4)
        Date: 2024-05-05 18:00:36 +0000
```

**Comment by mrvladus** [comment]
Try to run flatpak `kill io.github.mrvladus.List` first then launch in terminal

**Comment by rightpad** [comment]
I restarted my system, updated the application to 46.0.4, cleared the application data and ran `flatpak run io.github.mrvladus.List`. I was able to run the application and successfully setup my Nextcloud sync. The problem seems to have gone away. Thank you for your help!
