### ISSUE TITLE
App detaches from the command line when launched.

### ISSUE THREAD

**Issue by ponychicken** [mrvladus/Errands#259]
I have problems with the sync, so I wanted to have a look at std out.
Unfortunately the process detaches when I launch it in the terminal.
(The app starts, but the command in the terminal returns 0 and I cannot see further output.)

```
flatpak run -v io.github.mrvladus.List 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
......
F: Cleaning up unused container id 809219570
F: Allocated instance id 1393228666
F: Add defaults in dir /io/github/mrvladus/List/
F: Add locks in dir /io/github/mrvladus/List/
F: Allowing dri access
F: Allowing wayland access
F: Running 'bwrap --args 41 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 41 errands'

```

**Comment by mrvladus** [comment]
Try to run flatpak kill io.github.mrvladus.List first, then launch in terminal with flatpak run io.github.mrvladus.List

**Comment by mrvladus** [comment]
Or click Quit from main menu

**Comment by ponychicken** [comment]
Ah ok i get it, it was running in the background. I guess there is nothing to do here.
