### ISSUE TITLE
Add UI Feedback that server address needs http://

### ISSUE THREAD

**Issue by ponychicken** [mrvladus/Errands#261]
The UI lets me add an adress like 127.0.0.1 just fine without any indication that only http://127.0.0.1 will actually work.

Possible solutions:
- Preface any adress w/o a scheme automatically
- Warn the users about address without schemes

**Comment by mrvladus** [comment]
I'll add info popup button inside url entry.

**Comment by mrvladus** [comment]
Added in [46.0.5](https://github.com/mrvladus/Errands/releases/tag/46.0.5)

**Comment by ponychicken** [comment]
Thanks!
