### ISSUE TITLE
Add an option to hide completed items

### ISSUE THREAD

**Issue by ponychicken** [mrvladus/Errands#263]
Sorry for opening so many issues. If it annoys you let me know :)

I use Tasks on Android on the same WebDAV list. It marks Tasks as completed and doesnt't delete them.
So one of my list has 1500 entries, of which 1480 are completed.

In the Menu/Overview I would prefer to see the number of open items instead, because the number of total items is meaningless.
And in the List view, unless I am searching for something specific, I don't need the completed items as well, at max the completed items of today.

**Comment by mrvladus** [comment]
> In the Menu/Overview I would prefer to see the number of open items instead, because the number of total items is meaningless.

I'll make this like in header bar of task list: "num_of_completed / num_of_total"

> And in the List view, unless I am searching for something specific, I don't need the completed items as well, at max the completed items of today.

There is toggle in headerbar to hide completed tasks

**Comment by mrvladus** [comment]
Fixed in  [46.0.5](https://github.com/mrvladus/Errands/releases/tag/46.0.5)
