### ISSUE TITLE
Todays View is missing overdue tasks from yesterday

### ISSUE THREAD

**Issue by ponychicken** [mrvladus/Errands#264]
If I fail to complete a task yesterday, it does not appear in the today view, I suppose because the due date is not strictly today.

When querying task to display for the today view, the expected would be so select those which are
a) open and b) due date today or earlier

**Comment by mrvladus** [comment]
I added all previous due tasks to today page. Now every task that was planned earlier than today will be on this page and will be having red accent color on its date button like this:

![Снимок экрана от 2024-05-08 20-10-23](https://github.com/mrvladus/Errands/assets/64690334/2747541f-aca3-4b43-abc9-cb3cfb6924cf)

**Comment by mrvladus** [comment]
Fixed in [46.0.5](https://github.com/mrvladus/Errands/releases/tag/46.0.5)
