### ISSUE TITLE
Add Pomodoro Timer

### ISSUE THREAD

**Issue by golf1487** [mrvladus/Errands#269]
There is another Gnome circle pomodoro app **[Solanum](https://apps.gnome.org/en/Solanum/)**
To prevent jumping from one tool to another, Errands should have pomodoro integrated.
50 mins of work / 10 mins of break / 30 mins of long break after 4 cycles.
I think each task should have a little pomodoro icon. We do one task at a time for productivity.

**Comment by mrvladus** [comment]
I'm planning to add plugin support, so anyone can add this type of functionality, but I don't think this will be in the core features of the app.
