### ISSUE TITLE
Don't bind Ctrl+A to creating new list

### ISSUE THREAD

**Issue by TomaszGasior** [mrvladus/Errands#270]
Traditionally, Ctrl+A is used for selecting all text in currently focused input field. After recent updates, Errands binds Ctrl+A to creating new list dialog. Typing when creating new items on the list is frustrating because of that. Please don't bind any actions to Ctrl+A or at least don't interrupt GTK's input field built-in behaviour.

https://github.com/mrvladus/Errands/assets/1395027/bf8c289a-4c71-4238-9e82-784a1a83345b

46.0.4, Flatpak

**Comment by mrvladus** [comment]
Fixed in 0952502ef5009f679e49ef036e2797c0f1f990c6. Will be in the next update.
