### ISSUE TITLE
Export failed when a task(s) has sub-tasks

### ISSUE THREAD

**Issue by ColbyB722** [mrvladus/Errands#273]
Exporting with tasks that have sub-tasks fails to export. There will be a little toast notification on the bottom that says "Export failed" and then another that says "Exported". The resulting exported ics file does not import any tasks.

**Comment by ColbyB722** [comment]
Issue might be more complicated than I thought. It seems export is failing even with a single task in the list and a clean install

**Comment by ColbyB722** [comment]
Ok tired to recreate the issue on My Intel Wayland device running the same OS(Fedora 40-kernel 6.8.9) and build (46.0.5) and I can actually export from it. My X11 Ryzen-Nvidia machine device seems to be having an issue.

**Comment by mrvladus** [comment]
Confirm this. Fixed in 0a859902acb6776535d7c33bb6f77a3dc0bb41b8. Forgot to change file write mode. I'll make release now.

**Comment by mrvladus** [comment]
Pushed update to Flathub.
