### ISSUE TITLE
Notifications of long finished tasks

### ISSUE THREAD

**Issue by Sesivany** [mrvladus/Errands#276]
When I start Errands I now get notifications of tasks that were finished a long time ago. I don't set "start" dates, only "due" dates. Due dates of these tasks are long past and and the tasks are marked as finished. I receive notifications of them anyway. This started occurring recently.

**Comment by Sesivany** [comment]
Not same, it seemed to be random. But yesterday I deleted all finished tasks to stop it, so I can't reproduce it any more. Let's see if it starts occurring once I build a history of finished tasks again.

**Comment by mrvladus** [comment]
In the 46.1.1 it should be fixed.
