### ISSUE TITLE
Make it easier to edit task name

### ISSUE THREAD

**Issue by TomaszGasior** [mrvladus/Errands#277]
Currently, it's a little bit hard to edit title of existing task. You need three clicks in specific UI elements to be able to edit task name. Please make that easier.

I have a few ides for UI solution to make edit action fast and easy, like:
- double click to edit task name or
- mouse or touch long press to edit task name or
- secondary button click to edit task name.

46.0.4, Flatpak

**Comment by mrvladus** [comment]
I came up with this idea: use right-click menu for actions directly related to task-managment and move them from toolbar menu, leaving it to toolbar stuff only. Like this:

![Снимок экрана от 2024-05-15 12-38-40](https://github.com/mrvladus/Errands/assets/64690334/f7439eff-81cb-42f5-a443-9142fb81e884)
![Снимок экрана от 2024-05-15 12-38-24](https://github.com/mrvladus/Errands/assets/64690334/cb6c3ae5-a34f-4d40-b7ce-4d2feec4b23b)

**Comment by M00NJ** [comment]
I think the simplest and most intuitive way would be to make the task name string editable by just clicking on it. Currently clicking on a task expands it, but I think there is more than enough space left to click for the expand action, if the task name is clickable as well.

**Comment by mrvladus** [comment]
@M00NJ I think right-click is simple enough. I don't want to add more buttons to task, cause on mobile sreens it's very noticeable and eats up a lot of space.

**Comment by Roy-Orbison** [comment]
Double-click to edit would be a nice enhancement without a visual change, at least on desktop.

**Comment by mrvladus** [comment]
> Double-click to edit would be a nice enhancement without a visual change, at least on desktop.

Good idea!

**Comment by Roy-Orbison** [comment]
And if you can swing ‘Esc to cancel editing’, too, that would be awesome 😉. It would be more consistent with other program's edit boxes, like file managers. I looked through the docs for `Adw.EntryRow` and parent classes, but didn't see anything obvious that would do this.

**Comment by mrvladus** [comment]
In #427 I use GtkEditableLabel so it has that Esc function.
