### ISSUE TITLE
Does it support Recurrence?

### ISSUE THREAD

**Issue by abbluiz** [mrvladus/Errands#292]
I understand this app does not support recurrent tasks. Am I right? Because if I complete a recurrent task through Errands, in my other CalDAV-enabled services, the next task is not there anymore (it shows as completed as if it were a single task with no recurrence).

**Comment by mrvladus** [comment]
It doesn't yet. It will be later. #90

**Comment by abbluiz** [comment]
> It doesn't yet. It will be later. #90

Right. Thanks for replying quickly, your work is greatly appreciated!
