### ISSUE TITLE
Tray icon not showing Debian 12 KDE Wayland | 46.2.2

### ISSUE THREAD

**Issue by Jeefongithub** [mrvladus/Errands#314]
I recently noticed the tray icon is not showing when with the option toggled to run in background. 

![image](https://github.com/mrvladus/Errands/assets/53583661/438354cb-af03-4f2c-93ff-18e9a7fd72cb)

![image](https://github.com/mrvladus/Errands/assets/53583661/2fbc734c-d858-4bc4-9128-dfb353c2f439)

**Comment by mrvladus** [comment]
There is no tray icon in Errands. It only shows in GNOME quick settings menu.

**Comment by Jeefongithub** [comment]
it used to show a tray icon but changed fairly recently. Not sure if it was on my OS side or on the application side but it was nice since i could have it open without a taskbar entry

**Comment by mrvladus** [comment]
It was probably KDE thing then, because I've never used tray icon libraries.

**Comment by Sheikhm007** [comment]
> There is no tray icon in Errands. It only shows in GNOME quick settings menu.

What do you mean by quick settings menu? Are you referring to the menu I have attached in the screenshot? 

![Image](https://github.com/user-attachments/assets/f9850be9-c172-47e3-b26e-9cf6ad2ad436) 

If yes, how do i show errands in here?

**Comment by mrvladus** [comment]
Yes, in this menu, but only when it runs in the background as flatpak. But you can only close it from there anyway, there is no other actions that you can do with it.
