### ISSUE TITLE
Is there any possibility of synchronizing with the Google account?

### ISSUE THREAD

**Issue by MarleyS439** [mrvladus/Errands#328]
I would like to know if there is a way to enable or if there is any idea of ​​synchronizing with Google Agenda | Tasks the tasks.

**Comment by mrvladus** [comment]
Nope, only through CalDAV providers. Google technically supports it, but it's not allowing to create calendars and tasks, so I won't be able to add support for that.

**Comment by MarleyS439** [comment]
It really is a shame! The app is very good.
