### ISSUE TITLE
Google Tasks support not working

### ISSUE THREAD

**Issue by leftbas65** [mrvladus/Errands#355]
I replaced the SSD in my laptop and installed Debian Testing fresh, and now I'm attempting to get Errands to pick up Google Tasks but no dice. I installed the DEB package as well as the Flatpak (one after the other, not simultaneously), and removed and re-added my Google account but I got nothin'. Has Google support been removed or am I missing something?

**Comment by mrvladus** [comment]
Errands never supported Google Tasks, or Google Calendar.

**Comment by leftbas65** [comment]
Sorry, I think I was getting Errands mixed up with Endeavor.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
