### ISSUE TITLE
Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by Melluish** [mrvladus/Errands#37]
Installed from Software Manager on Linux Mint 21.2.

Application doesn't run:

```
$ flatpak run io.github.mrvladus.List
```
 
Just outputs the following and returns to prompt:

```
[DEBUG] Starting Errands 44.7.1
```

**Comment by mrvladus** [comment]
Please try to remove folder at ~/.var/app/io.github.mrvladus.List
Just make a copy first

**Comment by mrvladus** [comment]
And another question: did you just installed it or updated from previous version?

**Comment by mrvladus** [comment]
Just tested in the Linux Mint VM. Application runs fine. Maybe it's a flatpak bug? I've had similar isues with Chrome and Firefox.

**Comment by Melluish** [comment]
Great, thanks. Removing that folder worked.
