### ISSUE TITLE
CalDAV Integration

### ISSUE THREAD

**Issue by Baumistlustig** [mrvladus/Errands#4]
# CalDAV Integration

Hey there, 
I recently found your App in the Gnome Software center and I love it. It's simple, and does what it has to do. 

The only thing I'd wish for is an integration with the Nextcloud Tasks App. It would help me sync everything across my devices, so I wanted to ask if there are any plans for something like that.

**Comment by mrvladus** [comment]
Hello! I've never used Nextcloud before, so I don't really know how it works. I will look into that! Syncing is a good idea, so I can try to make it work.

**Comment by snydox** [comment]
> > Hello! I've never used Nextcloud before, so I don't really know how it works. I will look into that! Syncing is a good idea, so I can try to make it work.
> 
> You could integrate it with GNOME (which supports Nextcloud Tasks) like Endeavour (https://gitlab.gnome.org/World/Endeavour) does.

I actually stopped using Endeavour because it constantly crashes. Literally, it closes when it's idle.

**Comment by Baumistlustig** [comment]
> > > Hello! I've never used Nextcloud before, so I don't really know how it works. I will look into that! Syncing is a good idea, so I can try to make it work.
> > 
> > 
> > You could integrate it with GNOME (which supports Nextcloud Tasks) like Endeavour (https://gitlab.gnome.org/World/Endeavour) does.
> 
> I actually stopped using Endeavour because it constantly crashes. Literally, it closes when it's idle.

Same here. That, and the fact that sync also doesn't work properly, is the reason I thought about this one here.

**Comment by LSeelig** [comment]
Second the GNOME integration. Endeavor simply doesn't work. The only other simpler client is "Remembrance" but it hasn't been touched by the dev since May, and it only syncs with Microsoft ToDo.

**Comment by rafaelmardojai** [comment]
Probably this should be renamed to CalDAV support? Nextcloud Tasks doesn't have an API per-se.

**Comment by mrvladus** [comment]
Little update on the issue. I'm planning to add Nextcloud sync in the next couple of updates. I'll try to add Todoist sync option too.

**Comment by Julian4711** [comment]
That is great news :)
Keep it up!

**Comment by LSeelig** [comment]
> Little update on the issue. I'm planning to add Nextcloud sync in the next couple of updates. I'll try to add Todoist sync option too.

If you're integrating CalDAV, will this work for the default provider in GNOME, or only specifically enabled services?

**Comment by mrvladus** [comment]
I think this will be a setting for each provider, because not everyone is using GNOME, and this way I can make sync with multiple providers at the same time if needed.

**Comment by gremo** [comment]
Hi, thank you for you app :) it would be nice supporting also Google Keep, if possible :+1:

**Comment by mrvladus** [comment]
> Hi, thank you for you app :) it would be nice supporting also Google Keep, if possible 👍

You can open new issue for it, I'll look into that.

**Comment by mrvladus** [comment]
Hello everyone! I've pushed all of the sync code into main branch. I think it's working now, but if you can test it and report any problems, I would be happy to fix them :) You can use instruction in the README for that. Logs located at `~/.var/app/io.github.mrvladus.List.Devel/data/list/log.txt` and `~/.var/app/io.github.mrvladus.List.Devel/data/list/log.old.txt` for previous launch of the app.

**Comment by ekasprzak** [comment]
> Hello everyone! I've pushed all of the sync code into main branch. I think it's working now, but if you can test it and report any problems, I would be happy to fix them :) You can use instruction in the README for that. Logs located at `~/.var/app/io.github.mrvladus.List.Devel/data/list/log.txt` and `~/.var/app/io.github.mrvladus.List.Devel/data/list/log.old.txt` for previous launch of the app.

Awesome, thanks!

I just started testing it – as I understand it, Errands will **NOT** synchronize with currently existing calendars/lists, but it will use only “Errands” calendar that is created (if it doesn't exist) during first sync, correct?

If yes – is that the final approach/design, or maybe do you plan in some future to operate on multiple calendars/lists (including sync currently existing ones)?

**Comment by mrvladus** [comment]
Correct! It will only use Errands calendar. It is not a full CalDAV client for now :) Because it only has one list of tasks. But I have plans to add creation of multiple lists and therefore it would be possible to do full sync of calendars.

**Comment by Julian4711** [comment]
I am just testing it and it works very smoothly!
Thank you so much, a tool like that was really missing from the gnome desktop (since endeaver is broken beyond repair).

Some ideas for improvement:
* Add a button to test the nextcloud connection below the settings. 
* Automatically try to add https:// to the server URL if the user does not enter it
* For as long as you don't have that option to sync multiple lists, let the user specify that one list to sync (enter a name, default option could be Errands)

Also, are you planning to implement some of the caldav task attributes like priority, start date, end date, % completed and so on? 
It would be nice to make use of the colors somehow. Maybe have an optional connection high priority = red, medium = yellow or so.

**Comment by mrvladus** [comment]
Thank you for feedback!

> * Add a button to test the nextcloud connection below the settings.

Added Test button

> * Automatically try to add https:// to the server URL if the user does not enter it

Added, but only http:// (not everyone setting up SSL)

> * For as long as you don't have that option to sync multiple lists, let the user specify that one list to sync (enter a name, default option could be Errands)

Added calendar name field

> Also, are you planning to implement some of the caldav task attributes like priority, start date, end date, % completed and so on? It would be nice to make use of the colors somehow. Maybe have an optional connection high priority = red, medium = yellow or so.

I didn't think about that, but it's not difficult to implement in the future

**Comment by Julian4711** [comment]
Wow thank you, that was quick. :+1:

**Comment by mrvladus** [comment]
I've added sync option for "Other CalDAV Provider" for anything other than Nextcloud, but be careful - it needs full DAV url, for example: `https://www.google.com/calendar/dav/`

**Comment by Baumistlustig** [comment]
Sorry for the late answer to this thread, but i was a bit busy the last week. I now tried sync the first time and it works like a charm! If I encounter any bugs I'll open an issue!

**Comment by moedn** [comment]
Thousand thanks for integrating this! I was looking for a years for an app like that :purple_heart: :pray: 

Just downloaded the latest release via flathub and tried to connect to my nextcloud; entered the Data and clicked on `Test`; got the following error:

![image](https://github.com/mrvladus/Errands/assets/45949491/72398cff-258a-444c-8e32-a6f4eccf02fd)

(which doesn't really say much)

also the newly appeared sync button in the main window doesn't do much/anything: task list stays empty

same when I switch `Sync Provider` from `Nextcloud` to `CalDav`.

Would love to provide some logs; is there any way to do so?

**Comment by mrvladus** [comment]
logs at ~/.var/app/io.github.mrvladus.List/data/list/

**Comment by dehahost** [comment]
Hi,
I would like to report a bug in the Nextcloud sync - after configuring it in Preferences and clicking "Test" button,  "Connected" message pops up, but in the log I found the following:

```text
[DEBUG] Initialize sync provider
[INFO] Initialize Nextcloud sync provider
[INFO] Connected to Nextcloud server at 'https://<domain>/remote.php/dav/'
[ERROR] Can't connect to Nextcloud server at 'https://<domain>/remote.php/dav/'
```

I am using fresh Flatpak installation of Errands v45.0.3 on Kubutnu 23.04. Nextcloud version is 27.1.1.

**Comment by mrvladus** [comment]
@dehahost it's fixed in 45.0.4. Update will be on flathub in a couple hours

**Comment by moedn** [comment]
awesome! thank you @mrvladus :rocket: 

when I try to connect now (provider=nextcloud) I receive a `connected` notice. However, I still need to test it since I don't see any tasks or lists yet when I sync, but this could also be a problem on my end.

just for understanding: does Errands support multiple lists (= multiple calDAV calendars) at the moment? or will it try to find a "default" task list on nextcloud instead?

**Comment by mrvladus** [comment]
@moedn 
In the next release I'll make sync button appear in the header bar as soon as sync provider is selected so it won't be necessary to test connection or reload the app.
For now it only supports one calendar, by default it will create calendar named "Errands" if calendar name field is empty. You can change or create calendars by changing this field. I will work on this. Multiple calendars support is the next major release priority.

**Comment by moedn** [comment]
Awesome! multiple calendars support would be a crucial feature for me :pray: 

just wanted to test it on a nextcloud calendar, but for some reason the app refuses to load now; opened a new issue on this (#81)

**Comment by i2sage** [comment]
> Little update on the issue. I'm planning to add Nextcloud sync in the next couple of updates. I'll try to add Todoist sync option too.

is Todoist sync list on the upcoming features list?

**Comment by mrvladus** [comment]
@i2sage not yet. For now I'm focused on full CalDAV integration. I'm still planning to do it in the future ;)
