### ISSUE TITLE
'Cancel' still clears trash

### ISSUE THREAD

**Issue by TheKrafter** [mrvladus/Errands#42]
The 'cancel' button in the confirmation dialog when clearing trash still clears deleted todo items.

Repro:
1. Create a task and delete it
1. Press the trash icon in the deleted tasks panel
1. Press 'Cancel' in the dialog that pops up
1. Your task is still removed

Running the flatpak.

**Comment by mrvladus** [comment]
Thanks! It is fixed in [44.7.4](https://github.com/mrvladus/Errands/releases/tag/44.7.4)
