### ISSUE TITLE
'Restore all' brings back previously cleared sub-tasks

### ISSUE THREAD

**Issue by CastelJeremy** [mrvladus/Errands#44]
- Version: 44.7.4 (Flatpak)

If you delete a sub-tasks, clear the trash then delete a second sub-tasks and use 'Restore all' without restarting the app. Both sub-tasks are back inside the task.
Restarting the app between steps 5 and 6 fixes this issue.

1. Create a task
2. Create 2 sub-tasks inside the task
3. Delete a sub-task
4. Clear the trash
5. Delete the other sub-task
6. Restore All from trash
7. Both sub-task are back

**Comment by mrvladus** [comment]
Thanks for report! Found the problem. Will be fixed tomorrow.

**Comment by mrvladus** [comment]
Fixed in [44.7.5](https://github.com/mrvladus/Errands/releases/tag/44.7.5). Took a little bit longer that expected :)
