### ISSUE TITLE
Move task to subtask

### ISSUE THREAD

**Issue by Vicente015** [mrvladus/Errands#45]
I don't know if it would be possible but I would like to move a task to the subtasks of another task.

For example:
1. Apples
3. Shopping list
    - Bananas
  
I want to move "Apples" inside "Shopping list" ideally using drag and drop

**Comment by mrvladus** [comment]
Currently working on that 😄

**Comment by mrvladus** [comment]
Added in [44.7.5](https://github.com/mrvladus/Errands/releases/tag/44.7.5). Flathub update will be available in a few hours.

**Comment by Vicente015** [comment]
Thanks! Great work ;)
