### ISSUE TITLE
How do I switch to the dark mode?

### ISSUE THREAD

**Issue by afro-coder** [mrvladus/Errands#49]
Hi, I don't see the option to switch to dark mode, and the GTK vars don't do anything.

Any pointers on how to do this?

**Comment by mrvladus** [comment]
Hello! The app supports global dark theme. Or you want to set dark theme only for that app?

**Comment by afro-coder** [comment]
Hi, I'm not on Gnome, the global theme I have is Arc-dark, and since this is flatpak it by default seems to use only Adwaita, even from the code I read. I did find a way to switch to dark theme just now 
https://discourse.flathub.org/t/gtk4-apps-do-not-use-adwaita-dark/1327/2 

but it seems like the UI doesn't like it the color icons for the task disappear, I can't take a screenshot unfortunately

**Comment by mrvladus** [comment]
I see. I'll add setting to switch to dark mode manually.

**Comment by mrvladus** [comment]
What distro do you use btw? I wanna test it.

**Comment by afro-coder** [comment]
I'm on arch with i3wm, and happy to help with the testing too!

**Comment by mrvladus** [comment]
Added setting for theme in [44.7.5](https://github.com/mrvladus/Errands/releases/tag/44.7.5). Flathub update will be available in a few hours.
