### ISSUE TITLE
Collapse sub-tasks by default

### ISSUE THREAD

**Issue by TheKrafter** [mrvladus/Errands#50]
A Task with lots of sub-tasks can take up a lot of room. When Errands is launched, it should have these collapsed by default rather than expanded as they currently are. 

An indication that a task has sub-tasks that are not visible would probably be in order aswell.

**Comment by mrvladus** [comment]
I'll add setting for it in  preferences.

**Comment by mrvladus** [comment]
Added in [44.7.6](https://github.com/mrvladus/Errands/releases/tag/44.7.6)
