### ISSUE TITLE
[Question] Where is the data store of the application?

### ISSUE THREAD

**Issue by andersonpem** [mrvladus/Errands#62]
Hi. First things first. Your software is amazing. It follows the Gnome design language delightfully.

Where is the data store of the tasks, notes, etc? 

I'm planning on sync my two computers with Google Drive :)

Thank you very much.

Andy.

**Comment by andersonpem** [comment]
I found it. At least on the flatpak variant :)
`$HOME/.var/app/io.github.mrvladus.List/data`

Closing.
Thank you for your great software.

**Comment by mrvladus** [comment]
Thank you! I'm glad you like it:) Can you test it with google drive and report how it goes? Because I use Nextcloud specific url "http://myserver.com/remote.php/dav/". I add `/remote.php/dav/` last part for any adress

**Comment by andersonpem** [comment]
> 

Yes. But I do use [InSync](https://www.insynchq.com/), it usually avoids sync conflicts. I'll report back.
Thank you :smile:

**Comment by mrvladus** [comment]
I can add option in settings like "Other CalDAV Provider" and it won't be modifying url

**Comment by mrvladus** [comment]
Well... I've added this option 😄 So you can use it now, I've tested it, seems like it's working.
