### ISSUE TITLE
Feature request to schedule tasks 

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#63]
Hi!

This is only an idea and not super refined yet. I just wanted to get it out  to see how you would like it.

Now that Errands has integrated caldav, it will become a routine for me to use it. Whenever I think of something that needs to be done, I will add it to Errands (or to tasks.org on mobile, as I already do). 

But in order to actually commit time for the tasks and work on them, I have to schedule them in the calendar. 
So what if Errands had a feature where I could see my calendar entries and then drag & drop tasks into the calendar? 

The caldav task structure was originally designed for calendar appointments. Basically tasks are appointments without a date set.

What do you think?

**Comment by mrvladus** [comment]
Сan you describe in more detail? I don’t really understand what you mean.

**Comment by Julian4711** [comment]
Sure.  It's about planning your tasks easily by using a weekly calendar alongside the task list. All you need to do is drag and drop your tasks into the calendar and they will automatically become calendar entries. Ideally (but I don't think this is possible) you can drag the errands tasks directly into [Gnome Calendar](https://flathub.org/apps/org.gnome.Calendar).  

Since you have already integrated Caldav, converting tasks into appointments is technically no longer a big effort. As I said, in caldav tasks are essentially appointments without date and time.

**Comment by mrvladus** [comment]
I think I can make a button to open task in default calendar app... Just need to convert it to temporary .ics file and open it in the same time with xdg-open, that could work.

**Comment by Julian4711** [comment]
Sounds like a great idea. Could you implement it that way?
I hope I will not be the only person using it. ;)

**Comment by mrvladus** [comment]
I've tested this idea. It works :) I'll add this in one of the next updates.

**Comment by Julian4711** [comment]
It's not in the latest update, is it?
I couldn't find it in 45.0.4

**Comment by mrvladus** [comment]
No, it will probably be in 45.0.6 or 45.1

**Comment by mrvladus** [comment]
Added export task as ".ics" file in [45.1](https://github.com/mrvladus/Errands/releases/tag/45.1)., so it can be opened by any calendar app.
