### ISSUE TITLE
Nextcloud - empty task list

### ISSUE THREAD

**Issue by lightonflux** [mrvladus/Errands#66]
Hello, i tried the nextcloud settings. Both with 

* https://[myDomain]/remote.php/dav/calendars/[USER]/[NAME]/
*  https://[myDomain]/remote.php/

but the task list stays empty. The list is not empty on the server.

```[INFO] Sync tasks with Nextcloud
[DEBUG] Fetch tasks from Nextcloud
[DEBUG] No tasks on server
[DEBUG] Updating UI
[DEBUG] Initialize sync provider
```

The current UI doesn't guide the user at all. Personally i would prefer a wizard to enter nextcloud domain, user and password, and then select a task list that is already on my server.  Although i would prefer that the app supports multiple lists.

**Comment by mrvladus** [comment]
Hello! Just enter https://[myDomain] into URL field
And username with password in their own  fields

**Comment by mrvladus** [comment]
While I working on multiple lists support, I'll try to make it clearer in settings

**Comment by lightonflux** [comment]
I think i found the issue: I copied the list name from the URL, but it does not work. 

Create a list called "testö 🐛" which should have the url name "test" as the emoji and umlaut are not used in the nextcloud URL which can be obtained from nextcloud. Then errands creates a new list called test which will be empty. 

Inputting the name with the emoji will not work at all.

**Comment by lightonflux** [comment]
Somehow naming a task list with one emoji works. But to get the confirmation button (blue checkmark) you need to add a space. "🐛" vs "🐛 ".

**Comment by lightonflux** [comment]
I copied  the human readable names from nextcloud and it works. So i will close this issue. 

Can you tell me what the libawaita component of the textfield is called, so i can create an issue in their tracker?

**Comment by mrvladus** [comment]
Its AdwEntryRow
