### ISSUE TITLE
Nextcloud: changing task lists does not clear tasks

### ISSUE THREAD

**Issue by lightonflux** [mrvladus/Errands#69]
I changed the task list in the config several times. Old entries from the previous task list stay in the app and maybe even get added to the new task list.

**Comment by mrvladus** [comment]
Found the issue. Fixed. Will be in the next release. Thank you for report!

**Comment by mrvladus** [comment]
Fixed in [45.0.2](https://github.com/mrvladus/Errands/releases/tag/45.0.2)
