### ISSUE TITLE
Moving a finished task inside a different finished task unfinishes both

### ISSUE THREAD

**Issue by niktss** [mrvladus/Errands#72]
Pretty much the title; all subtasks also get unfinished

Screen recording:
https://github.com/mrvladus/Errands/assets/57101103/a23d7ac5-ba91-4405-a0ae-13af5f24dc33

**Comment by mrvladus** [comment]
Yep... It's a bug. Only top-level task should be uncompleted, all the sub-tasks should be untouched. I'll fix that, thanks!

**Comment by niktss** [comment]
If both tasks are finished, shouldn't both stay finished? Maybe the user just wants to reshuffle/reorganize. Though if an unfinished task becomes a subtask of a finished one, then I agree the parent should get unfinished as well

**Comment by mrvladus** [comment]
This behavior, when task becomes unfinished when sub-task moved or added to it, is pretty much the standard with todo apps like this.
