### ISSUE TITLE
redundant share path

### ISSUE THREAD

**Issue by jbicha** [mrvladus/Errands#79]
Debian's lintian checker pointed out that `/usr/share/errands/errands/` is redundant. Probably only need one _errands_ there.

```
/usr/share/errands/errands.gresource
/usr/share/errands/errands/
/usr/share/errands/errands/utils/
/usr/share/errands/errands/utils/animation.py
/usr/share/errands/errands/utils/data.py
/usr/share/errands/errands/utils/functions.py
/usr/share/errands/errands/utils/gsettings.py
/usr/share/errands/errands/utils/logging.py
/usr/share/errands/errands/utils/markup.py
/usr/share/errands/errands/utils/sync.py
/usr/share/errands/errands/utils/tasks.py
/usr/share/errands/errands/widgets/
/usr/share/errands/errands/widgets/preferences.py
/usr/share/errands/errands/widgets/task.py
/usr/share/errands/errands/widgets/trash_item.py
/usr/share/errands/errands/widgets/window.py
```

**Comment by mrvladus** [comment]
The first folder is app data folder and second "errands" folder is a python module folder. Iit suppose to be like that :)

**Comment by mrvladus** [comment]
For example, [Dialect](https://github.com/dialect-app/dialect) and [Blanket](https://github.com/rafaelmardojai/blanket) both written in pytnon and use the same approach to module directory, so I do not see the problem with that, it is not a python library, and can be named as developer wants, it just more convenient that way.
