### ISSUE TITLE
Store sync password safely

### ISSUE THREAD

**Issue by cheywood** [mrvladus/Errands#80]
Firstly congratulations on Errands :smile: 

Ideally the sync password would be stored encrypted. I gather you don't want to depend on GNOME, but perhaps you could eg. use the secret service when it's available?

**Comment by mrvladus** [comment]
I'll look into that

**Comment by sophie-h** [comment]
Please use [libsecret](http://lazka.github.io/pgi-docs/#Secret-1) to store the password. The libsecret docs also provide a python example:

- https://gnome.pages.gitlab.gnome.org/libsecret/libsecret-python-examples.html

On behalf of the Circle Committee I would ask you to treat this issue with a higher priority.

**Comment by mrvladus** [comment]
@sophie-h I'll use it in the next release
