### ISSUE TITLE
Errands refuses to load

### ISSUE THREAD

**Issue by moedn** [mrvladus/Errands#81]
`flatpak run io.github.mrvladus.List`

gives:

```
[DEBUG] Starting Errands 45.0.4
Failed to register: Timeout was reached
```

System: Fedora 38; Kernel 6.5.6-200.fc38.x86_64

unfortunately, I can't provide much more info than that – the last `log.txt` also only contains `[DEBUG] Starting Errands 45.0.4`

**Comment by mrvladus** [comment]
Did you tried to reboot? Some times flatpak is buggy after updates.

**Comment by moedn** [comment]
good to know :)

but nope, still refuses to load. However, the log slightly changed:

1. attempt to load (right after boot)

```
[DEBUG] Starting Errands 45.0.4
[DEBUG] Initialize GSettings
[DEBUG] Initialize sync provider
[INFO] Initialize Nextcloud sync provider
```

2. attempt to load from terminal (after nothing happened)

```
[DEBUG] Starting Errands 45.0.4
Failed to register: Timeout was reached
```

**Comment by mrvladus** [comment]
1. Backup file with tasks `~/.var/app/io.github.mrvladus.List/data/list/data.json`
2. Delete folder `~/.var/app/io.github.mrvladus.List`
3. Try to run the app
4. Import tasks from that backup file

**Comment by mrvladus** [comment]
Make sure your system is updated!

**Comment by moedn** [comment]
hey there!

followed the steps, but the app still refuses to load. the folder however is created anew, log still says

`[DEBUG] Starting Errands 45.0.4`

I'll update my system at home (on mobile data right now) and let you know if anything changes (which I would expect honestly, since the app seemed to work fine until very recently)

thanks!! :heart:

**Comment by moedn** [comment]
System updated, but no success…

```
[DEBUG] Starting Errands 45.0.4
Failed to register: Timeout was reached
```

**Comment by mrvladus** [comment]
Can you try latest build  from main branch with Gnome Builder?

**Comment by mrvladus** [comment]
Is there any chance that Errands in `~/.config/autostart/`?

**Comment by mrvladus** [comment]
Or try to run `killall -9 errands` in terminal.

**Comment by moedn** [comment]
hey there! I've been struggling around with gnome builder to test the app, but didn't succeed (not much of a coder :)  )

instead I reinstalled the app and now it loads fine :ok_hand: I'd thereby close this issue until further notice
