### ISSUE TITLE
Text legibility

### ISSUE THREAD

**Issue by iru2x** [mrvladus/Errands#82]
![image](https://github.com/mrvladus/Errands/assets/133756704/bd1d6bdd-b910-4283-9ae2-f40dfb8fdb3a)

Can you see the url? me neither. :rofl: 

Come'on there should be a text usability module in every development toolkits that avoids this kind of things...

[some source](https://m2.material.io/design/color/text-legibility.html#text-backgrounds)
[more source](https://www.uxmatters.com/mt/archives/2007/01/applying-color-theory-to-digital-displays.php)

**Comment by mrvladus** [comment]
Missed that, thank you! Just will add white text color for links on dark theme in css.

**Comment by iru2x** [comment]
You too! :wink:

**Comment by mrvladus** [comment]
Fixed in [45.0.5](https://github.com/mrvladus/Errands/releases/tag/45.0.5)
