### ISSUE TITLE
Ability to add describtion to tasks and sub-tasks

### ISSUE THREAD

**Issue by marek-lach** [mrvladus/Errands#88]
It would be nice to be able to add a more detailed one line elaborated description to a task, or sub-task, that could look something like this, where the task title has a big font, whereas task description has small font:

![Screenshot from 2023-10-26 21-56-10](https://github.com/mrvladus/Errands/assets/45913977/9e151cbf-a452-4fde-9721-4b960fa2145b)

**Comment by mrvladus** [comment]
Hi! I think it's not very useful, because this space is occupied by status of completed tasks. And in the next release I'll add option to add notes to tasks anyway :)

**Comment by marek-lach** [comment]
> Hi! I think it's not very useful, because this space is occupied by status of completed tasks. And in the next release I'll add option to add notes to tasks anyway :)

That seems a good solution!
