### ISSUE TITLE
multiple calendars

### ISSUE THREAD

**Issue by carlnickel** [mrvladus/Errands#89]
I love the sync implementation, its working fine, thank your for that! Now I can use it with the android app tasks.org 
with tasks, i am used to sort tasks in different calendars, such as "work", "private", "home", whatever. do you think you could provide a way to easily switch between calendar lists?

**Comment by mrvladus** [comment]
I'm working on that right now :) It will be added in 45.1 release.

**Comment by carlnickel** [comment]
Awesome! Thank you:)

Am 29. Oktober 2023 20:00:42 MEZ schrieb mrvladus ***@***.***>:

**Comment by cichy1173** [comment]
@mrvladus Waiting for this feature! This is the first GTK TODO app with Nextcloud sync and subtask support that I found!

**Comment by madhums** [comment]
Same here. @mrvladus do you have an ETA when 45.1 will be released?

**Comment by mrvladus** [comment]
@madhums probably in couple of days

**Comment by mrvladus** [comment]
Added support for multiple lists and calendars in [45.1](https://github.com/mrvladus/Errands/releases/tag/45.1). It was sooner than a couple of days :)
