### ISSUE TITLE
GTK critical because of the shape of the widget tree

### ISSUE THREAD

**Issue by tyrylu** [mrvladus/Errands#96]
Under at least GTK 4.12, because the task list has GtkRevealers as children, not GtkListBoxRows as the GtkListBox focus code expects, it generates a GTK critical when the list box grab focus handler tries to find the list from a row, because it expects the list to be the direct parent of the row.

**Comment by mrvladus** [comment]
Fixed the issue today, in the next release it won't be happening anymore. I just replaced AdwActionRow with custom GtkBox.

**Comment by mrvladus** [comment]
Fixed in [45.1](https://github.com/mrvladus/Errands/releases/tag/45.1).
